### ISSUE TITLE
Disable some effects?

### ISSUE THREAD

**Issue by R3tr0Ananas** [Mikihero/BetterCoinflips#3]
Is there a way to disable some effects or does it need to be added?

**Comment by Mikihero** [comment]
> Is there a way to disable some effects or does it need to be added?
> 

It's not exactly a feature yet but you could just set an effects trigger chance to 0. This would disable that specific effect. This won't work for the LightBulb effect and the FakeCassie effect since they are the last effect on their respective list of effects and have to be chosen if no other before them is.   I will address this issue and officially add such feature (since now it's just a biproduct of the % chances update) in the next version.

**Comment by R3tr0Ananas** [comment]
Maybe add on coinflip it removes the coin out of your inv

**Comment by Mikihero** [comment]
> Maybe add on coinflip it removes the coin out of your inv

Probably something I should've thought of myself, I will implement it in the next update just as the feature we discussed before.

**Comment by Mikihero** [comment]
> Maybe add on coinflip it removes the coin out of your inv

It has since been added, the other feature can still be done the way I explained before aka just setting the chance of that effect to 0 tho it still comes with the downsides I explained earlier. I will have to think of a way to circumvent this for the future tho.
