### ISSUE TITLE
don't workin while in offline mode

### ISSUE THREAD

**Issue by tuesay** [Mikihero/BetterCoinflips#30]
![изображение_2024-01-19_152110098](https://github.com/Mikihero/BetterCoinflips/assets/102454920/f8a3e814-68e6-4447-a4f6-35adb7a32381)
when im startin in online mod, all works fine, but this throws me an exception when im trying to flip the coin in offline mode
is this a issue or should it be?
or how to make it work so that it works

**Comment by Mikihero** [comment]
I have no experience with offline mode but as far as I can a huge part of exiled doesn't work correctly or at all with offline mode enabled (pretty sure most of the stuff in the Player class simply can't work in offline mode). I will not be making this plugin work for offline mode because of those things. If you want to make it work you'd have to rewrite huge portions of it.

**Comment by tuesay** [comment]
Oh.
I got it, I didn't know that, thank you.
