### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by LaFesta1749** [Mikihero/BetterCoinflips#7]
Since the last Exiled update Version 6.0.0-beta.26 is there gonna be an update to this plugin? I really like it and would be sad to see it gone forever :(

**Comment by Mikihero** [comment]
There are currently several bugs with exiled since it's still in beta that prevent me from fully updating the plugin. I'm pretty source code in this repo is up to date, and if you build it yourself it should mostly work, tho some features will be broken. I will work on the full release once the bugs in question are fixed or once EXILED 6 comes out of beta.

**Comment by LaFesta1749** [comment]
Thank you for the latest update.
